#include <stdio.h>
#include <getopt.h>

static const struct option long_opts[] = {
    {"output", required_argument, 0, 'o'},
    {NULL, 0, 0, 0}
};

int main(int argc, char** argv)
{
    int ret;
    opterr = 0;
    while((ret = getopt_long(argc, argv, "o:", long_opts, NULL)) != -1)
    {
        if(ret == 'o') {
            FILE* f = fopen(optarg, "w");
            if(!f)
                return 1;
            fputs("This file is generated by nodoc because pandoc is not available on this system.\n", f);
            fclose(f);
        }
    }
    return 0;
}
